server:
  port: 8081

application:
  name: ms-gateway

base:
  service:
    uri: http://201.95.98.141:8082
    name: base-service
    context-path: /base/v1/**

jwt:
  secret: fbad2abb4f9b599f8eb41d7ac6a3fc836fc2cbbdfbad2abb4f9b599f8eb41d7ac6a3fc836fc2cbbd
  expiration: 86400

logging:
  level:
    web: DEBUG