server:
  port: 8081

application:
  name: GATEWAY-SERVICE

base:
  service:
    uri: http://192.168.15.200:8080
    name: base-service
    context-path: /base/v1/**


logging:
  level:
    web: DEBUG