server:
  port: 8080

application:
  name: GATEWAY-SERVICE

base:
  service:
    uri: http://localhost:8081
    name: base-service
    context-path: /base/v1/**

jwt:
  secret: fbad2abb4f9b599f8eb41d7ac6a3fc836fc2cbbdfbad2abb4f9b599f8eb41d7ac6a3fc836fc2cbbd
  expiration: 86400

logging:
  level:
    web: DEBUG