server:
  port: 8081

application:
  name: GATEWAY-SERVICE

base:
  service:
    uri: http://192.168.15.200:8080
    name: base-service
    context-path: /base/v1/**

route:
  open:
    endpoint: /auth/register
jwt:
  secret: fbad2abb4f9b599f8eb41d7ac6a3fc836fc2cbbd

logging:
  level:
    web: DEBUG