server:
  port: 8080
  servlet:
    context-path: /base/v1

spring:
  main:
    banner-mode: console
  application:
    name: base services
  datasource:
    url: jdbc:mysql://192.168.15.200:3306/epic_db?useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
logging:
  level:
    web: DEBUG